### ISSUE TITLE
Qq

### ISSUE THREAD

**Issue by lllmel** [Axel791/TelegramBotGarant#1]
Hi мне нужна помощь с ботом ,сможешь помочь ?

**Comment by Axel791** [comment]
привет, в чем проблема?

**Comment by lllmel** [comment]
Мне в боте нужно ошибки исправить
Тоже бот автогарант собственно.
Есть ошибки при совершении сделок ,при завершении,сам не могу исправить,в общем довести до ума надо эту темку,за помощь подкину монет.
Да и если поможешь буду в дальнейшем обращаться.
Сможешь помочь?

**Comment by lllmel** [comment]
вот допустим на кнопку ВЫВОД нажал
![image](https://user-images.githubusercontent.com/59796476/204861792-e9382a7c-a4fa-4452-a616-45da45ff55f5.png)

мне нужен фулл код, по трэйсу не пойму

**Comment by Axel791** [comment]
смогу, в тг напиши мне: @kazakov_tm
